### ISSUE TITLE
AttributeError: module 'src.pymodal_surgical.modal_analysis.functions' has no attribute 'calculate_motion_spectrum'

### ISSUE THREAD

**Issue by fyushan** [mikelitu/pymodsurgical#12]

**Comment by mikelitu** [comment]
Dear @fyushan,

Thank you for using this repository.

Could you give me a bit more of information on how to reproduce the error? A screenshot of the terminal should be enough for me to have a bit more information of what it is actually happening. Also, could you let me know how you installed the package?
